//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeReader2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_cikis
    {
        public int Id { get; set; }
        public string Siparis_No { get; set; }
        public string Kalem_Sayisi { get; set; }
        public string Toplam_Fiyat { get; set; }
        public string Siparis_Durumu { get; set; }
        public string Kargoya_sonVerme { get; set; }
        public string Kargo_FirmaAdı { get; set; }
        public string Musteri_Ad { get; set; }
        public string Teslimat_Adres { get; set; }
        public Nullable<int> Barkod { get; set; }
    
        public virtual Tbl_Urunler Tbl_Urunler { get; set; }
    }
}
